### ISSUE TITLE
GhostBSD not booting

### ISSUE THREAD

**Issue by luis0V** [ghostbsd/issues#1]
### Version

22.06.18

### Explain the issue and what happens

I installed GhostBSD and it didn't boot. the ISO wasn't corrupted, mi BIOS was configured correctly and i had the hardware necessary to install it, i tried installing a second time and the same happens, it just wouldn't boot.

### Explain how to reproduce the bug?

Just install it

**Comment by ericbsd** [comment]
Is the last build 23.05.28 fixed the issue? https://www.ghostbsd.org/download#latest_builds

**Comment by ericbsd** [comment]
Closing this issue for lake of output
