### ISSUE TITLE
Homepage spam/seo links

### ISSUE THREAD

**Issue by robn** [ghostbsd/issues#140]
### Version

0

### What desktop?

Other

### Explain the issue and what happens

There's a whole bunch of what look like spam/seo links at the bottom of https://ghostbsd.org/. I'm guessing you're not sponsored by a bunch of building/cleaning contractors? (nice work if you are, non-tech sponsors are tough to get!)

Sorry if this isn't the best place to report it; didn't see it mentioned in forums or elsewhere.

### Explain how to reproduce the bug?

- Open homepage.
- Let the uncertainty flow over you.

**Comment by ericbsd** [comment]
These are legitimate sponsors although the list might need a clean up. There is some the might have reach eol.

**Comment by robn** [comment]
I am rarely surprised, but you got me. Ok, thanks! :D

**Comment by ericbsd** [comment]
I reworked the partners and sponsors section on the front page.

![image](https://github.com/user-attachments/assets/1c76fc70-8aec-4dc5-989c-56077ef17470)
