### ISSUE TITLE
update-station not running

### ISSUE THREAD

**Issue by tim-pearce** [ghostbsd/issues#143]
### Version

23.10.1

### What desktop?

Community XFCE

### Explain the issue and what happens

I haven't had the update station icon appear for some time.
I ran it manually from the menu and nothing happened.
I ran it in a terminal emulator and got
`sudo update-station check-now`
`Traceback (most recent call last):`
`  File "/usr/local/bin/update-station", line 15, in <module>`
`   import distro`
`ModuleNotFoundError: No module named 'distro'`

Ran

`sudo pkg install update-station`
`Updating GhostBSD repository catalogue...`
`GhostBSD repository is up to date.`
`All repositories are up to date.`
`The following 2 package(s) will be affected (of 0 checked):`
``
`New packages to be INSTALLED:`
`	py39-distro: 1.9.0`
``
`Installed packages to be UPGRADED:`
`	update-station: 4.8 -> 4.9`

It now runs. 

I am still reluctant to try it as update to 24.01.1 on two PCs with the command line instructions has failed.

### Explain how to reproduce the bug?

Wait forever for the update station icon to appear!

**Comment by tim-pearce** [comment]
I have run update-station.
I am still on 23.10.1 XFCE but maybe now the upgrade to 24.01.1 might work and as I type this update-station has just informed me that a 'Major version upgrade' is available.

**Comment by ericbsd** [comment]
Distro was missing in XFCE, so I added it as a dependency to Update Station to ensure its installation. I forgot to close that issue since has been resolved just a bit before this issue was made.
