### ISSUE TITLE
Website compromised - ghostbsd.org

### ISSUE THREAD

**Issue by tril0byte** [ghostbsd/issues#144]
### Version

N/A

### What is the security issue or vulnerability?

List of sponsors includes a bunch of SEO spam links

### Security issue or vulnerability information

Ghostbsd.org viewed on android scroll down past the sponsor banners and lots of spam urls

**Comment by tril0byte** [comment]
Wait, are all these Concrete contractors links from people who paid sponsorships? If I pay $5/month with PayPal does the website automatically post whatever link and text I choose?

**Comment by ericbsd** [comment]
They are sponsors. The website is not compromised. They are manually added.

**Comment by ericbsd** [comment]
I reworked the partners and sponsors section on the front page.

![image](https://github.com/user-attachments/assets/7f9568ae-63db-4712-aa53-a65a1c7ceb5c)
