### ISSUE TITLE
Build www/chromium with necessary options to watch e.g. Netflix

### ISSUE THREAD

**Issue by q-pa** [ghostbsd/issues#145]
### Describe the feature or enhancement.

Make the build-adjustments to have a chromium version on GhostBSD which enables the user to watch online streaming services like Netflix, Disney+ etc.

### Why this request?

The necessary options are not enabled by default in the FreeBSD port. Lots of users use the linux-browser-installer (compat/ubuntu) or are forced to build the ports themselves. Having a GhostBSD package would make this much simpler, especially for beginners. 

Here is one way to install Widevine on GhostBSD.

(1)  sudo pkg install foreign-cdm
(2)  sudo pkg install src
(3)  sudo pkg install ports
(4)  cd /usr/ports/www/linux-widevine-cdm
(5) sudo make install

Here is how to make Chromium work with Widevine.

(1)  sudo pkg install bash bsddialog portconfig gperf flock py39-jinja2 py39-ply py39-html5lib node v4l_compat xcb-proto usbids libva mesa-dri qt5-core qt5-widgets  os-generic-userland-devtools
(2)  cd www/chromium
(4)  sudo make config
(4a)  Enable WIDEVINE
(4b)  Enable PULSEAUDIO
(4c)  Disable SNDIO
(5)  sudo make -j4 DISABLE_VULNERABILITIES=yes 
(6) sudo make install

**Comment by grahamperrin** [comment]
> (4b) Enable PULSEAUDIO
> (4c) Disable SNDIO

Maybe unnecessary, if using 125.0.6422.76 or greater as built for FreeBSD ports: 

- https://github.com/FreeBSD/freebsd-ports/commit/6acad34cb2bc3b858f64724620fd3c11b2a602f3

**Comment by grahamperrin** [comment]
> (4a) Enable WIDEVINE

Will licencing allow a GhostBSD repo to provide a package with this enabled? 

https://github.com/FreeBSD/freebsd-ports/commit/7a12c6c96ac266f40f62de9a4281808054de609b was: 

> **www/linux-widevine-cdm: Widevine DRM plugin from Google.**
> 
> This port was decoupled from the www/foreign-cdm port to not violate redistribution restrictions of Google's license.

**Comment by q-pa** [comment]
This can be closed for I found another solution:

1. pkg install chromium
2. pkg install foreign-cdm
3. install port /usr/ports/www/linux-widevine-cdm
4. pkg install ungoogled-chromium
5. cp -r /usr/local/share/chromium/WidevineCdm /usr/local/share/ungoogled-chromium/
6. pkg delete chromium
7.  use ungoogled-chromium to stream DRM content

**Comment by ericbsd** [comment]
foreign-cdm will be installed with Chromium automatically, but because of the license agreement, linux-widevine-cdm will need to be installed from ports.
