### ISSUE TITLE
Difference of time display between lock/login screen and normal desktop

### ISSUE THREAD

**Issue by hanmesoft** [ghostbsd/issues#15]
### Version

23.09.06

### Explain the issue and what happens

I'm in Korea, Asia. I set timezone as "Seoul/Asia". But I found the time display was not on local time.

Look these. 

https://www.os2.kr/data/editor/2309/thumb-19fc424f56ac26104acc7019709f8aab_1694501994_5012_600x450.jpg

https://www.os2.kr/data/editor/2309/thumb-19fc424f56ac26104acc7019709f8aab_1694501996_0581_600x450.jpg

These two are displaying 12:33:54 on monday.

And look this.

https://www.os2.kr/data/editor/2309/thumb-19fc424f56ac26104acc7019709f8aab_1694501996_8597_600x450.jpg

Local time is 21:35:00 on monday. 

### Explain how to reproduce the bug?

If you change the timezone, you can see this difference.

**Comment by ericbsd** [comment]
This must mean your system is not set to local time or the OS is not set to local time.

Can you see if your system has /etc/wall_cmos_clock exit? If not, open a terminal and do `sudo touch /etc/wall_cmos_clock`.

This file should exist but it depends on when that system was installed.

**Comment by hanmesoft** [comment]
I did what you wrote. I found that there was a file "wall_cmos_clock" but still there were time difference.

**Comment by ericbsd** [comment]
did you try to remove wall_cmos_clock if it fixes your issue looks like your system is set to UTC time and not local time.

**Comment by hanmesoft** [comment]
I did that. But no change. T.T

**Comment by ericbsd** [comment]
Oh, sorry, I forgot to answer that is weird.

Did you try to use tzsetup in the terminal?

**Comment by hanmesoft** [comment]
I did with tzsetup in the terminal. Now I can see same time in the desktop and in the waiting screen. But that's UTC and 8 hours advance. I'll try more and let you know. 

Thank you.

**Comment by hanmesoft** [comment]
Finally, I got success due to your support.

1. Checking H/W date and time.
2. Checking "/etc/wall_cmos_clock"
3. Changing local time with tzsetup 

Now, it works well. 

Thank you.
