### ISSUE TITLE
old.ghostbsd.org certificate expired

### ISSUE THREAD

**Issue by grahamperrin** [ghostbsd/issues#151]
### Version

not applicable

### What desktop?

Other

### Explain the issue and what happens

Expired: 

- Friday, 14th Jun 2024 15:12:04 GMT.

DNS names: 

- `download.ghostbsd.org`
- `old.ghostbsd.org`
- `wiki.ghostbsd.org`

### Explain how to reproduce the bug?

1. Visit (for example) <https://wiki.ghostbsd.org/index.php/Desktop_Environment>
2. `SEC_ERROR_EXPIRED_CERTIFICATE`

### What is the Expected behavior (if applicable)

Certification :-)

**Comment by ericbsd** [comment]
When I renewed it, I forgot to restart the service.

**Comment by ericbsd** [comment]
Thanks for reporting

**Comment by grahamperrin** [comment]
Thanks! (This repo probably wasn't the proper place for an unusual report.)

**Comment by ericbsd** [comment]
This is the place where you can report any issues.
