### ISSUE TITLE
Latest update does not have latest firefox 129

### ISSUE THREAD

**Issue by sestarus13** [ghostbsd/issues#166]
### Version

24.01.01

### What desktop?

Official MATE

### Explain the issue and what happens

There was an update today and there was no any update to Firefox

### Explain how to reproduce the bug?

open ff, help, about.

### What is the Expected behavior (if applicable)

it should show 129

### Additional context (if applicable)

lets hope that other sw is updated

**Comment by ericbsd** [comment]
The last update was to upgrade to PKGBASE. A build is currently underway that should bring Firefox to the latest version before the end of the weekend.

I am closing this since it is in progress.
