### ISSUE TITLE
ghostbsd.org - unrelated (spam?) links on homepage

### ISSUE THREAD

**Issue by rtomsick** [ghostbsd/issues#168]
### Version

ALL

### What desktop?

Other

### Explain the issue and what happens

Visiting ghostbsd.org I see a bunch of seemingly-unrelated links at the bottom of the page (under the sponsor logos, the last of which appears to be Codefirst).

Given that some of them are both local and the sort of categories that SEO is commonly used for, it's unclear whether these are sponsors or a successful hack to juice search ranking.

### Explain how to reproduce the bug?

Visit ghostbsd.org, scroll to bottom of page (Sponsors section)

### Additional context (if applicable)

Apologies for reporting here.  I didn't see (or missed!) contact info for the website itself.  Thanks!

**Comment by ericbsd** [comment]
These are all paid link.

**Comment by ericbsd** [comment]
I have reworked the Partners and Sponsors I hope it looks less spammy.
![image](https://github.com/user-attachments/assets/963f97a2-8568-4274-a66c-4d7bb23974e3)
