### ISSUE TITLE
Set our system and software packagtes has vital packages

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/issues#169]
### Describe the feature or enhancement.

This feature prevents the removal of default packages by accident.

### Why this request?

See why here https://forums.ghostbsd.org/viewtopic.php?f=69&t=2525

**Comment by grahamperrin** [comment]
A comparison (for reference only): two vital packages with FreeBSD pkgbase. 

```text
% pkg query -e '%o = base && %V = 1' '%o/%n' | wc -l
       2
% pkg query -e '%o = base && %V = 1' '%o/%n' 
base/FreeBSD-clibs
base/FreeBSD-runtime
% uname -aKU
FreeBSD mowa219-gjp4-zbook-freebsd 15.0-CURRENT FreeBSD 15.0-CURRENT main-n272124-2b7f2890a812 GENERIC amd64 1500023 1500023
% 
```

I do understand the wish for GhostBSD to have vitality for a broader set of packages. 

Noted, with thanks: 

- #174
