### ISSUE TITLE
live session doesn't start

### ISSUE THREAD

**Issue by ksso00** [ghostbsd/issues#172]
### Version

24.07.1

### What desktop?

Official MATE

### Explain the issue and what happens

the last version 24.07.1 doesnt start live session in an old laptop where previous version could be loaded and started
however, in the same laptop the previous version could be upgraded to 24.07.1

just freezes with the main theme of ghostbsd after entering the first options (multiuser)
thanks

### Explain how to reproduce the bug?

try to install /run last version 24.07.1

### What is the Expected behavior (if applicable)

run iive session and install

### Additional context (if applicable)

in a modern laptop (ssd) the live session starts quite slowly and does not have wifi

thanks

**Comment by GLwd40** [comment]
Unfortunately, it's the same on VMware.

![Zrzut ekranu 2024-09-04 154035](https://github.com/user-attachments/assets/c26a5d3b-8a35-461e-aba9-5169287257b0)

**Comment by ericbsd** [comment]
There is a bug with the legacy boot that I reported to FreeBSD: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281278

I am actively trying to find the issue.

**Comment by ericbsd** [comment]
This should be fixed by tomorrow if this https://github.com/ghostbsd/ghostbsd-src/pull/342 is the issue. It is most likely it.

**Comment by ericbsd** [comment]
OK, there is a test ISO here https://ci.ghostbsd.org/jenkins/job/stable-14/job/Verify%20The%20ISO%20Build%20With%20Unstable%20Packages/35/.

This is fixed for VMs and my ThinkPad T530.

**Comment by ericbsd** [comment]
After adding a new feature to protect the default packages, I will release a new iso.
