### ISSUE TITLE
RStudio crashing

### ISSUE THREAD

**Issue by q-pa** [ghostbsd/issues#180]
### Version

24.04.2

### What desktop?

Official MATE

### Explain the issue and what happens

Installed RStudio package. When I start it from the CLI I get the following error: 
ld-elf.so.1: /usr/local/lib/rstudio/bin/rstudio: Undefined symbol "_ZNSt13exception_ptr31__from_native_exception_pointerEPv"

### Explain how to reproduce the bug?

see above

### What is the Expected behavior (if applicable)

RStudio starting

**Comment by q-pa** [comment]
FYI, a web search did not find anything related. Therefore, this might be a GhostBSD issue.

**Comment by ericbsd** [comment]
Packages are built for 24.07.3, so that could be the issue.

**Comment by ericbsd** [comment]
I just tested the package, and it is working on 24.07.3.

**Comment by q-pa** [comment]
Works after updating to 24.07.3.
