### ISSUE TITLE
Error starting Update-Station

### ISSUE THREAD

**Issue by q-pa** [ghostbsd/issues#190]
### Version

24.10.1

### What desktop?

Official MATE

### Explain the issue and what happens

Output starting Update-Station from the CLI:

```
update-station

Traceback (most recent call last):
  File "/usr/local/bin/update-station", line 14, in <module>
    from update_station.notification import UpdateNotifier, TrayIcon
ModuleNotFoundError: No module named 'update_station'
```

### Explain how to reproduce the bug?

do the above

### What is the Expected behavior (if applicable)

GUI front end of Update-Station starts

**Comment by ericbsd** [comment]
Thanks for reporting this. I made a mistake in the plist of the port. I am working on it right away.

**Comment by ericbsd** [comment]
I fixed the package. To fix the issue, you must run `sudo pkg upgrade -f update-station`.
