### ISSUE TITLE
Removving UFS supports from the installer.

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/issues#26]

**Comment by Coderdreams** [comment]
Please don't do this, for some old PCs ZFS is too much and not worth it.

**Comment by ericbsd** [comment]
Hard from 2010 and onward runs fine on ZFS and GhostBSD is going all in on ZFS only.

**Comment by Coderdreams** [comment]
I've experienced bad FS corruption on computers without redundant HDDs and ZFS that wasn't fixable with the usual fsck tools, that's why I stopped using it and rely on old trusty UFS for those cases.

**Comment by ericbsd** [comment]
In that case, FreeBSD will still be available with UFS.
