### ISSUE TITLE
32-bin wine issue: wine [wine-7.0.2] and wine64 [wine-8.0.2] versions do not match!

### ISSUE THREAD

**Issue by q-pa** [ghostbsd/issues#28]
### Version

23.10.1

### Explain the issue and what happens

The title is the error message when starting winecfg. One should
try updating 32-bit wine with
	`/usr/local/share/wine/pkg32.sh upgrade`

But the packages are up to date. 

### Explain how to reproduce the bug?

repeat the above

**Comment by ericbsd** [comment]
I started to work on this., but forgot to return to it. Thanks for the reminder.

**Comment by ericbsd** [comment]
The repos are up to date.

**Comment by ericbsd** [comment]
### To do
- [ ] Add automation to build i386 jails.
- [ ] Add automation to build i386 packages.
- [ ] Add automation to send packages to all mirrors.

**Comment by q-pa** [comment]
Thanks a lot for the quick fix!

**Comment by q-pa** [comment]
Little reminder, since today's updates: 
`wine [wine-7.0.2] and wine64 [wine-8.0.2] versions do not match!`

**Comment by ericbsd** [comment]
I am working on adding the automation so I do not have to do it manually.

**Comment by q-pa** [comment]
Thanks a lot. Funny thing is, on one of my systems I can run the upgrade and 65 candidates are found. On another I only get:

```
/usr/local/share/wine/pkg32.sh upgrade
pkg -o ABI=FreeBSD:13:i386 -o INSTALL_AS_USER=true -o RUN_SCRIPTS=false --rootdir /home/username/.i386-wine-pkg upgrade
Updating GhostBSD repository catalogue...
GhostBSD repository is up to date.
All repositories are up to date.
Checking for upgrades (0 candidates): 100%
Processing candidates (0 candidates): 100%
Checking integrity... done (0 conflicting)
Your packages are up to date.
```

Rebooting, even reinstalling did not help.

**Comment by q-pa** [comment]
Can confirm the aforementioned on my third system. So it is 2 out of 3 where pkg32 upgrade returns 0 candidates.

**Comment by q-pa** [comment]
Sorry for the noise... Now it three out of three.

**Comment by ericbsd** [comment]
The packages will be out soon.

**Comment by ericbsd** [comment]
The new packages are out. They will be built and sent automatically with future package updates.

**Comment by q-pa** [comment]
Thanks a lot for the quick fix!
