### ISSUE TITLE
ghost update plus kde packages ------causing crash during boot--- unrecognised? ,touch screen-- recognised but froze.

### ISSUE THREAD

**Issue by triffid-4** [ghostbsd/issues#3]
### Version

23.04.23

### Explain the issue and what happens

computer froze after boot script wrote touch screen plus usb(I did not understand)?
===========
I was booting in safe mode, single user,verbose.
I had just installed kde software for ghostbsd. 
Had functioned without touch screen before periodic upgrade and installation of packages from control center which should not have faulted.
P840 Toshiba satellite failed on update but non touch screen r50b, satellite is still working.
Also an X73 asus dropped into shell and would not load the window system after the update?
I do not know how to receive an answer. 
 

### Explain how to reproduce the bug?

Booting in safe, single user mode on P840 toshiba laptop after installing latest update plus kde ghost package.
booting is delayed or stops.

### What is the Expected behavior (if applicable)

recognise touch screen and install driver and continue boot.

### Additional context (if applicable)

stated touch screen on usb?

**Comment by ericbsd** [comment]
What did you use to update GhostBSD?

**Comment by triffid-4** [comment]
Quoting Eric Turgeon ***@***.***>:

> What did you use to update GhostBSD?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/ghostbsd/issues/issues/3#issuecomment-1565381739
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>
mr Turgeon,
I used the update station. There is an error, failed to resolve pool,  
on the working system? Could you fix this. Which book is good for  
freebsd?
Richard.

**Comment by ericbsd** [comment]
I am trying to understand this ticket, and there are too many things going on on this ticket. I do not understand the real problem here.

If you have multiple issues make sure to create a ticket for each issue and be clear on concise.

**Comment by ericbsd** [comment]
I am closing this for lack of feedback.
