### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by tim-pearce** [ghostbsd/issues#36]
### Version

23.10.09 (XFCE)

### Explain the issue and what happens

The update, using Update station fails.
The last two lines in the log are
[414/1338] Upgrading llvm15 from 15.0.7_6 to 15.0.7_7...
[414/1338] Extracting llvm15-15.0.7_7: ln: /usr/local/share/icons/hicolor/pixmaps/pixmaps: File exists
I tried deleting that file (it's actually a link) and run Update Station again. That just caused another similar error for some other file.
I rolled back to the backup environment and tried again with the same result.

Near
[update.txt](https://github.com/ghostbsd/issues/files/13275400/update.txt)
 the top of the log was
Checking integrity... done (3 conflicting)
  - perl5.34-5.34.1_3 conflicts with perl5-5.34.1_3 on /usr/local/bin/perl5.34.1
  - ghostscript10-10.02.0 conflicts with ghostscript9-agpl-base-9.56.1_12 on /usr/local/bin/dvipdf
  - ghostscript10-10.02.0 conflicts with ghostscript9-agpl-base-9.56.1_12 on /usr/local/bin/dvipdf
Cannot solve problem using SAT solver, trying another plan
Checking integrity... done (0 conflicting)
The following 1338 package(s) will be affected (of 0 checked):

Installed packages to be REMOVED:
	ghostscript9-agpl-base: 9.56.1_12

### Explain how to reproduce the bug?

Do an update.

**Comment by tim-pearce** [comment]
I noticed there is a llvm15-lite so I tried installing that. Doing so caused an upgrade to llvm15 and an error stating it couldn't install llvm15-lite because it installs files in the same place.
I now have llvm15-15.0.7_7 so hopefully when I try system update again it should work.

**Comment by tim-pearce** [comment]
Now ends with
[217/1338] Upgrading kf5-breeze-icons from 5.110.0 to 5.111.0...
[217/1338] Extracting kf5-breeze-icons-5.111.0: ..ln: /usr/local/share/icons/hicolor/pixmaps/pixmaps: File exists

**Comment by tim-pearce** [comment]
Pardon me for recording this here. I helps me keep track of it. The PC with the problem is not very fast and it's a big update.
After pre-updating the problem packages it now ends at
[87/1338] Reinstalling gdk-pixbuf2-2.42.10_1...
ln: /usr/local/share/icons/hicolor/pixmaps/pixmaps: File exists

Will now roll back and pre-update this package.

**Comment by tim-pearce** [comment]
Change of plan. Renamed the pixmaps link to pixmaps_not.

**Comment by tim-pearce** [comment]
Different error this time!
[418/1338] Upgrading ffmpeg from 6.0_3,1 to 6.0_5,1...
[418/1338] Extracting ffmpeg-6.0_5,1: .......... done
xmlcatmgr: entry already exists for `/usr/local/share/xml/xmlcharent/catalog' of type `CATALOG'

**Comment by ericbsd** [comment]
This is odd. I wonder what is causing this?

**Comment by tim-pearce** [comment]
This time
[188/1338] Reinstalling gtk3-3.24.34_1...
[188/1338] Extracting gtk3-3.24.34_1: .........xmlcatmgr: entry already exists for `/usr/local/share/xml/xmlcharent/catalog' of type `CATALOG'

**Comment by tim-pearce** [comment]
Each one seems to work fine using pkg upgrade.
Maybe it's because I might have got behind in updates although I didn't think I was that far behind.
Maybe something to do with the fact that this was a standard MATE install and I added XFCE. This PC and my laptop were XFCE installs from the beginning.
Hopefully I will come to an end to these cycles eventually.

**Comment by tim-pearce** [comment]
I will probably reinstall on this particular PC. It's not my main PC (I have 2 other GhostBSD PCs).
It was an early experiment in installing and using GhostBSD and I've probably installed a lot of unnecessary stuff along the way.
My intent was for it to replace my 'staff web site' machine that staff members use to search for articles that are no longer on our live web site for possible reuse.

**Comment by tim-pearce** [comment]
I was came across this page [https://easylinuxtipsproject.blogspot.com/p/fatal-mistakes.html](url) and one of the tips is "Don't mix desktop environments".
I think I have illustrated this point on this system!

**Comment by tim-pearce** [comment]
I tried to install GhostBSD 22.06.18 XFCE on this PC using the DVD I already have. I've used this on a laptop recently and it worked fine - I just had to run all the updates.
Previously I installed GhostBSD MATE. Don't recall which version but it was during this past year. My notes about the install say ‘monty’ has onboard graphics Intel 82Q35 Express GMA 3100 – pkg install xf86-video-intel. I couldn't get X to work this time.

I tried fixing the current install and at present it is working and Update Station says it is up to date. I've had to crash out of pkg and Update Station a few times.

`Uninstalled all MATE stuff (Don’t try to run multiple DEs on one system)

pkg autoremove
pkg delete “anything suspicious – in this case gtk2”
pkg update -f
pkg upgrade -f`

Now when I run pkg update -f  I get

`[1146/1217] Reinstalling ghostbsd-xfce-settings-3.7.3...
[1146/1217] Extracting ghostbsd-xfce-settings-3.7.3: 100%
/bin/sh: update-alternatives: not found
...
[1156/1217] Reinstalling xfce4-notifyd-0.9.2_1...
[1156/1217] Extracting xfce4-notifyd-0.9.2_1: 100%
[1157/1217] Reinstalling xfce4-timer-plugin-1.7.2_1...
[1157/1217] Extracting xfce4-timer-plugin-1.7.2_1: 100%
[1158/1217] Reinstalling xfce4-taskmanager-1.5.6...
[1158/1217] Extracting xfce4-taskmanager-1.5.6: 100%
[1159/1217] Reinstalling os-generic-userland-23.10.1...
[1159/1217] Extracting os-generic-userland-23.10.1: 100%
[1160/1217] Reinstalling beadm-1.3.5...
[1160/1217] Extracting beadm-1.3.5: 100%
[1161/1217] Reinstalling agame-1577_13...
[1161/1217] Extracting agame-1577_13: 100%
[1162/1217] Reinstalling pkg-1.20.9...
[1162/1217] Extracting pkg-1.20.9: 100%
[1163/1217] Reinstalling epson-inkjet-printer-escpr-1.7.26...
[1163/1217] Extracting epson-inkjet-printer-escpr-1.7.26: 100%
[1164/1217] Reinstalling libmypaint-1.6.1_2...
[1164/1217] Extracting libmypaint-1.6.1_2: 100%
[1165/1217] Reinstalling os-generic-kernel-23.10.1,1...
[1165/1217] Extracting os-generic-kernel-23.10.1,1: 100%
[1166/1217] Reinstalling ghostbsd-icons-1.8...
[1166/1217] Extracting ghostbsd-icons-1.8: 100%
Child process pid=2297 terminated abnormally: Killed    [After a very long time!]

[tim@monty /var/log]$ cat messages | grep reinstalled | tail
Dec 21 10:22:40 monty pkg[2297]: xfce4-notifyd reinstalled: 0.9.2_1 -> 0.9.2_1 
Dec 21 10:22:40 monty pkg[2297]: xfce4-timer-plugin reinstalled: 1.7.2_1 -> 1.7.2_1 
Dec 21 10:22:41 monty pkg[2297]: xfce4-taskmanager reinstalled: 1.5.6 -> 1.5.6 
Dec 21 10:22:41 monty pkg[2297]: os-generic-userland reinstalled: 23.10.1 -> 23.10.1 
Dec 21 10:22:41 monty pkg[2297]: beadm reinstalled: 1.3.5 -> 1.3.5 
Dec 21 10:22:41 monty pkg[2297]: agame reinstalled: 1577_13 -> 1577_13 
Dec 21 10:22:45 monty pkg[2297]: pkg reinstalled: 1.20.9 -> 1.20.9 
Dec 21 10:22:46 monty pkg[2297]: epson-inkjet-printer-escpr reinstalled: 1.7.26 -> 1.7.26 
Dec 21 10:22:47 monty pkg[2297]: libmypaint reinstalled: 1.6.1_2 -> 1.6.1_2 
Dec 21 10:22:55 monty pkg[2297]: os-generic-kernel reinstalled: 23.10.1,1 -> 23.10.1,1 

tail messages
Dec 21 10:43:46 monty kernel: pid 2297 (pkg), jid 0, uid 0, was killed: failed to reclaim memory

I think there is a problem with gtk-update-icon-cache
`
Could the missing update-alternatives have something to do with it? Is that something that comes with the XFCE version?

**Comment by tim-pearce** [comment]
I think I've fixed it!
Previously I renamed /usr/local/share/pixmaps to /usr/local/share/pixmaps_not and then the system recreated /usr/local/share/pixmaps
This file is a link to /usr/local/share/pixmaps - ie recursive. It would seem gtk-update-icon-cache is somehow aware of this but not pixmaps_not 
I just ran pkg upgrade -f ghostbsd-icons and the only error was
Generating GTK icon cache for /usr/local/share/icons/Vivacious-Colors
gtk-update-icon-cache: The generated cache was invalid.

Full code:
sudo pkg upgrade -f ghostbsd-icons
Updating GhostBSD repository catalogue...
GhostBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be REINSTALLED:
	ghostbsd-icons-1.8

Number of packages to be reinstalled: 1

Proceed with this action? [y/N]: y
[1/1] Reinstalling ghostbsd-icons-1.8...
[1/1] Extracting ghostbsd-icons-1.8: 100%
gtk-update-icon-cache: Cache file created successfully.
==> Running trigger: gtk-update-icon-cache.ucl
Generating GTK icon cache for /usr/local/share/icons/Qogir
Generating GTK icon cache for /usr/local/share/icons/Vivacious-Colors
gtk-update-icon-cache: The generated cache was invalid.
Generating GTK icon cache for /usr/local/share/icons/Vivacious-Colors-Dark
Generating GTK icon cache for /usr/local/share/icons/Qogir-dark
Generating GTK icon cache for /usr/local/share/icons/Vivacious-Colors-Full-Dark
Generating GTK icon cache for /usr/local/share/icons/ghostbsd

**Comment by tim-pearce** [comment]
Lesson learnt!
