### ISSUE TITLE
PSI can't be started.

### ISSUE THREAD

**Issue by hansw-nlo** [ghostbsd/issues#41]
### Version

23.10.1

### Explain the issue and what happens

psi
ld-elf.so.1: /usr/local/lib/qt5/libQt5Xml.so.5: Undefined symbol "_ZTVNSt3__13pmr25monotonic_buffer_resourceE"

### Explain how to reproduce the bug?

Start psi from the terminal

### Additional context (if applicable)

It seems any software using qt5 is broken, it gives the same errors

**Comment by ericbsd** [comment]
I moved the issue to ghostbsd/issues.

**Comment by ericbsd** [comment]
Closed from the conclusion at https://github.com/ghostbsd/issues/issues/39#issuecomment-1807237199

**Comment by ericbsd** [comment]
Closed from the conclusion at https://github.com/ghostbsd/issues/issues/39#issuecomment-1807237199
