### ISSUE TITLE
Add graphics/qgis-ltr and graphics/qgis  to GhostBSD binary packages for installation to GhostBSD.  Already exists in FreeBSD

### ISSUE THREAD

**Issue by wb7odyfred** [ghostbsd/issues#5]
### Describe the feature or enhancement

Please place QGIS & QGIS-LTR into GhostBSD supported binary packages
QGIS is at 3.28.7 version number
QGIS-LTR is at 3.22 version number

### Why this request?

S P uses QGIS software in his daily work and wishes to use QGIS on his home GhostBSD computer

also **development manager view**  URL link is not working  https://github.com/orgs/ghostbsd/projects/4/views/12

[FreeBSD Pkgs 13  QGIS pkg ](https://freebsd.pkgs.org/13/freebsd-amd64/qgis-ltr-3.28.7_1.pkg.html)
[FreeBSD Ports QGIS for 13.1 ](https://github.com/freebsd/freebsd-ports/commit/3a44e4a8c0656a68575fbce6dd5b581f91d30dca)

[FreeBSD directory browser for QGIS port ](https://www.gitclear.com/open_repos/freebsd/freebsd-ports/browse?path=graphics%2Fqgis-ltr&start_tag=%5Bobject+Object%5D&end_tag=%5Bobject+Object%5D&filter_query=graphics%2Fqgis-ltr&file=graphics%2Fqgis-ltr%2FMakefile)

**Comment by ericbsd** [comment]
PDAL did not compile.

```
/wrkdirs/usr/ports/math/pdal/work/PDAL-2.3.0-src/pdal/Geometry.cpp:143:26: error: cannot initialize a variable of type 'OGRSpatialReference *' with an rvalue of type 'const OGRSpatialReference *'
    OGRSpatialReference *srs = m_geom->getSpatialReference();
                         ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/wrkdirs/usr/ports/math/pdal/work/PDAL-2.3.0-src/pdal/Geometry.cpp:162:26: error: cannot initialize a variable of type 'OGRSpatialReference *' with an rvalue of type 'const OGRSpatialReference *'
    OGRSpatialReference *inSrs = m_geom->getSpatialReference();
                         ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ericbsd** [comment]
I completely forgot to close this issue since it is available.
```
> pkg search qgis-ltr
qgis-ltr-3.28.9_1              Free and Open Source Geographic Information System
```
