### ISSUE TITLE
[Bug]: ISO installation gets stuck after reading EFI framebuffer information

### ISSUE THREAD

**Issue by kiyospace** [ghostbsd/issues#52]
### Version

22.06.18 & 22.07.28

### Explain the issue and what happens

I have been trying install and play with GhostBSD on VM (VirtualBox) for a while and basically everything works fine, so I thought let me try to install on my laptop, but the installation freezes every time as shown in the picture after reading EFI framebuffer information right after the boot and won't go on.

![ghostbsd_install_freezes](https://user-images.githubusercontent.com/92704328/181865802-01b96115-8f4d-45fa-86d7-f297c35e2ca9.jpg)

* My Laptop: HP ENVY13T with i7-8565U+16GB DDR4+NV GeForce MX250+4K Display
* Tested ISO (w/ USB) files:  GhostBSD-22.06.18.iso & GhostBSD-22.07.28.iso (Both get stuck at the same point shown in the picture every time)
* **Succeeded to finish the installation of FreeBSD-13.1-RELEASE-amd64** without problems (with ISO on the same USB Flash Disk) on the same Laptop...

### Explain how to reproduce the bug?

1. Download GhostBSD iso
2. Flash (dd write with rufus) the iso to the USB flash disk
3. Reboot and the system can boot to GhostBSD from the USB
4. system gets stuck after reading EFI framebuffer information as shown in the above picture every time

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues

**Comment by grahamperrin** [comment]
Ensure that a _copy of_ the loader in the EFI system partition matches the loader that is provided by GhostBSD. 

loader.efi(8) [EXAMPLES](https://man.freebsd.org/cgi/man.cgi?query=loader.efi&sektion=8&manpath=freebsd-release#EXAMPLES) are appropriate for FreeBSD, the routine for GhostBSD will differ (please see, for example, the foot of <https://www.ghostbsd.org/news/GhostBSD_24.01.1_Now_Available>). 

### Background

In Bugzilla for FreeBSD, my 2021 report [255073 – boot (UEFI): loader: copy_staging: no progress beyond EFI framebuffer information](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255073) became a duplicate of 2016 report [209821 – UEFI - installation media hangs when booting on ASUS P6P67 DELUXE](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=209821). 

For FreeBSD 13.1-RELEASE, <https://www.freebsd.org/releases/13.1R/relnotes/#boot> (2022-05-16) noted that UEFI boot was improved for amd64. No reference to any commit, however the various commits certainly did fix bugs such as 255073.

**Comment by grahamperrin** [comment]
FreeBSD Quarterly Status Report 3rd Quarter 2021: [Improved amd64 UEFI boot](https://www.freebsd.org/status/report-2021-07-2021-09/#_improved_amd64_uefi_boot)

**Comment by clark713** [comment]
Downloaded a new copy of Ghost and was able to install OK using the same
machine problem orig. happened on.  Thanks
