### ISSUE TITLE
Add progress for update-staiton the check-now option

### ISSUE THREAD

**Issue by wb7odyfred** [ghostbsd/issues#8]
### Version

23.06.22  

### Explain the issue and what happens

fred@fred-T440pc ~> update-station
fred@fred-T440pc ~> sudo update-station
/usr/local/bin/update-station:186: DeprecationWarning: Gtk.StatusIcon.set_tooltip_text is deprecated
  statusIcon.set_tooltip_text('Update Available')
/usr/local/bin/update-station:191: DeprecationWarning: Gtk.StatusIcon.set_visible is deprecated
  statusIcon.set_visible(False)
/usr/local/bin/update-station:192: DeprecationWarning: Gtk.StatusIcon.set_from_icon_name is deprecated
  statusIcon.set_from_icon_name('system-software-update')
pkg: Error extracting the archive: 'Lzma library error:  No progress is possible'
pkg: No signature found in the repository.  Can not validate against /usr/share/keys/ssl/certs/ghostbsd.cert key.
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
fred@fred-T440pc ~> update-station
fred@fred-T440pc ~> sudo update-station
/usr/local/bin/update-station:186: DeprecationWarning: Gtk.StatusIcon.set_tooltip_text is deprecated
  statusIcon.set_tooltip_text('Update Available')
/usr/local/bin/update-station:191: DeprecationWarning: Gtk.StatusIcon.set_visible is deprecated
  statusIcon.set_visible(False)
/usr/local/bin/update-station:192: DeprecationWarning: Gtk.StatusIcon.set_from_icon_name is deprecated
  statusIcon.set_from_icon_name('system-software-update')
pkg: Error extracting the archive: 'Lzma library error:  No progress is possible'
pkg: No signature found in the repository.  Can not validate against /usr/share/keys/ssl/certs/ghostbsd.cert key.

HIT CTRL-C  to kill hanging program.

^CTraceback (most recent call last):
  File "/usr/local/bin/update-station", line 800, in <module>
    Gtk.main()
  File "/usr/local/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 1689, in main
    return _Gtk_main(*args, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt

Newly installed GhostBSD, do not believe have used pkg application before.  This is error message I got from running  GUI Icons   System --> Administration ---> Update-Station

Will start via GUI Icons and try again.   This is a record of the error message.

Versions of Software available?

Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
fred@fred-T440pc ~> uname -aKmnopr
FreeBSD fred-T440pc 13.2-STABLE FreeBSD 13.2-STABLE GENERIC amd64 amd64 1302505
fred@fred-T440pc ~> uname -a
FreeBSD fred-T440pc 13.2-STABLE FreeBSD 13.2-STABLE GENERIC amd64
fred@fred-T440pc ~> ghostbsd-version --h
Illegal option --
usage: ghostbsd-version [-fkov]
fred@fred-T440pc ~ [1]> ghostbsd-version -fkov
13.2-STABLE
1302505
23.05.12
23.06.22

### Explain how to reproduce the bug?

GUI Icons   System --> Administration ---> Update-Station  Did not even display an Icon

### What is the Expected behavior (if applicable)

Expected behavior   is to be come a running program with a GUI and display icon.

**Comment by wb7odyfred** [comment]
![Update-Station_01_Screenshot at 2023-07-04 21-43-37](https://github.com/ghostbsd/issues/assets/8184041/2f5ee2ed-88c7-486a-91f4-12fbcee16ed6)
This 2nd or 3rd time , running,  I did get an icon that says "This computer is up to date"

**Comment by ericbsd** [comment]
GUI Icons System --> Administration --> Update-Station does not display an icon. I only started to look for updates/updates.

I think it is time to add a progress bar similar to the Ubuntu update manager.

Some things with a message looking for updates.

**Comment by ericbsd** [comment]
I updated the Title to reflect the change I will make with this ticket.

**Comment by ericbsd** [comment]
Pushing the update resolves this issue
