### ISSUE TITLE
chromium browser issues

### ISSUE THREAD

**Issue by epsheldoni** [ghostbsd/issues#9]
### Version

23.07.20

### Explain the issue and what happens

Launching chromium from Applications > Internet > Chromium does not render pages correctly.  Text does not show and some graphics do not show up

### Explain how to reproduce the bug?

launch Chromium from the Applications menu

### What is the Expected behavior (if applicable)

When I launch chromium from /usr.local/share/chromium/chrome all pages render correctly.  Also, going to /usr/local/share/chromium and clicking on chrome, the browser launches and performs correctly.

### Additional context (if applicable)

this behavior started after the latest packages update from the update station

**Comment by epsheldoni** [comment]
After first posting this, I later thought that all I have to do is just edit the menu entry to 
/usr/local/share/chromium/chrome %U.  After doing that, chromium launches and works correctly.

**Comment by ericbsd** [comment]
I am not able to reproduce this.

**Comment by ericbsd** [comment]
Does it still happen?

**Comment by epsheldoni** [comment]
-----Original Message-----

**Comment by epsheldoni** [comment]
-----Original Message-----
