### ISSUE TITLE
Cannot boot after zpool upgrade (24.01.1]

### ISSUE THREAD

**Issue by q-pa** [ghostbsd/issues#92]
### Version

24.01.1

### Explain the issue and what happens

Upgrade to 24.01.1 went smoothly. Then I followed the instructions here to upgrade my pool: https://www.ghostbsd.org/news/GhostBSD_24.01.1_Now_Available

ada0p1 is my EFI partition. There were no errors. But now the boot process halts with this screen: 
![2024-02-14-20-47-05-247](https://github.com/ghostbsd/issues/assets/3322553/9ae2f563-d06a-4c62-b4c8-a82b4250c5bd)

### Explain how to reproduce the bug?

see above

**Comment by ericbsd** [comment]
How old is your installation?

**Comment by q-pa** [comment]
Hard to say, around 1.5 years.

**Comment by q-pa** [comment]
It is a Lenovo Thinkpad T520, upgraded with an SSD and 16 GB RAM.

**Comment by ericbsd** [comment]
Could you try to boot from an ISO and redo the copy of the file but also copy in `EFI/BOOT/`.

**Comment by q-pa** [comment]
Yes! That worked. I already had a stick prepared and had checked the boot partition. Your idea was my guess, too. But I am very reluctant messing around with any boot settings and wanted to hear your opinion on that. Many thanks!!
