### ISSUE TITLE
No static ip address after upgrading to 24.01.1

### ISSUE THREAD

**Issue by stefan1241** [ghostbsd/issues#94]
### Version

24.01.1

### Explain the issue and what happens

I upgraded from GhostBSD 23.10.1 to 24.01.1 via update-station.

On GhostBSD 23.10.1 I configured a static ip address on my lan card (re0) and it always worked very well.

After the upgrade to 24.01.1 i can't assign a static ip address anymore. The lan card only works when I use
DHCP. The rc.conf file wasn't changed from 23.10.1 to 24.01.1

After booting GhostBSD 24.01.1 ifconfig looks like this:

re0: flags=1008802<BROADCAST,SIMPLEX,MULTICAST,LOWER_UP> metric 0 mtu 1500
	options=8209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>
	ether 70:85:c2:ff:71:69
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>

### Explain how to reproduce the bug?

Just boot GhostBSD 24.01.1 - no network available - no static ip address assigned to the network interface re0 

### What is the Expected behavior (if applicable)

after booting GhostBSD 24.01.1 network with a static ip address should be available on interface re0.

### Additional context (if applicable)

It seams that networkmanager causes this issue. I was able to reproduce the issue on a machine with FreeBSD 14.0 RELEASE.

Uninstalling or deactivating networkmanager solved the issue. After deactivating networkmanager GhostBSD 24.01.1 provides network services with a static ip address. This is ifconfig after booting into GhostBSD 24.01.1 without networkmanager:

re0: flags=1008843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST,LOWER_UP> metric 0 mtu 1500
	options=8209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>
	ether 70:85:c2:ff:71:69
	inet 19x.xxx.x.xxx netmask 0xffffff00 broadcast 19x.xxx.x.xxx
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>

**Comment by ericbsd** [comment]
I tested that on my desktop, and the static IP works fine.

Was the static IP setup with NetworkMgr?

**Comment by ericbsd** [comment]
On the second machine, I still had the same results. I set the static IP with NetworkMgr and rebooted, and everything is working.

**Comment by ericbsd** [comment]
That is what NetworkMgr sets in rc.conf.
```
ifconfig_igb0="inet 19x.xxx.xxx.xxx netmask 255.255.255.0"
defaultrouter="19x.xxx.xxx.xxx"
```

**Comment by stefan1241** [comment]
I normally set it directly in /etc/rc.conf. I also tried to set it in networkmanager but after reboot the static ip-address was not shown anymore. 
I have this issue on 2 desktop pc's. On my laptop everything works fine.

**Comment by ericbsd** [comment]
I have reproduced the issue after resuming from Suspend.

**Comment by ericbsd** [comment]
I might have found the issue. It looks related to auto-switch.py. It is run by devd and was done when GhostBSD was using OpenRC. I do not think we need it with FreeBSD intit. I will do some more testing and ensure the rest works fine.

**Comment by ericbsd** [comment]
I have been testing NetworkMgr without auto-switch.py, and the problem I see is when I unplug the wire connection, it does not auto-switch to the WiFi or the other nic. I am still working on a solution.

**Comment by alfbar** [comment]
I experienced a similar problem. After upgrading to 24.01.1 I don't get a IPV4 address via DHCP.
Executing "service dhclient start alc0" solves this problem for me - until reboot.
IMHO networkmgr seems to be the culprit.
In FreeBSD 14.0 I solved the issue by simply deinstalling networkmgr (only wired lan needed).
If necessary, I can provide more details.

**Comment by ericbsd** [comment]
The package is being built and will be added tomorrow.

**Comment by tschettervictor** [comment]
Im having this issue trying to run GhostBSD 24.01.1 in a TrueNAS CORE VM.

> I experienced a similar problem. After upgrading to 24.01.1 I don't get a IPV4 address via DHCP. Executing "service dhclient start alc0" solves this problem for me - until reboot. IMHO networkmgr seems to be the culprit. In FreeBSD 14.0 I solved the issue by simply deinstalling networkmgr (only wired lan needed). If necessary, I can provide more details.

This command `service dhclient start em0` seems to resolve the issue as well on boot.
